[package]
name = "ICT_log_maker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.25.0"
egui = "0.25.0"
env_logger = "0.10.1"
log = "0.4.20"
chrono = "0.4.31"
rand = "0.8.5"
